### ISSUE TITLE
Relative links in readme don't route correctly

### ISSUE THREAD

**Issue by MathijsHaakman** [builtforvue/ui#1]
When there is a relative link in the README.MD like `[Get started](/docs/installation.md)`, it will navigate to https://www.builtforvue.com/docs/installation.md instead of https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/installation.md

Example readme: https://www.builtforvue.com/#/matteo_gabriele/vue-analytics

**Comment by abishekrsrikaanth** [comment]
@MathijsHaakman, Thanks for the report. This should now be fixed
