### ISSUE TITLE
Github markdown emojis aren't displayed

### ISSUE THREAD

**Issue by MathijsHaakman** [builtforvue/ui#3]
Github has a special set of emojis [(see this link)](https://gist.github.com/rxaviers/7360908), which aren't displayed in your readme. It shows for example `:art:` instead of :art:

[Example BuiltForVue readme](https://www.builtforvue.com/#/michalsnik/eslint-plugin-vue)
[Corresponding Github readme](https://github.com/vuejs/eslint-plugin-vue)

**Comment by abishekrsrikaanth** [comment]
@MathijsHaakman, this should now be fixed.
