### ISSUE TITLE
Some emojis/characters aren't properly encoded in the readme

### ISSUE THREAD

**Issue by MathijsHaakman** [builtforvue/ui#4]
Characters such as `©` displays as `Â©` and `⚠️ `displays as `â ï¸`

Scroll to the bottom of these readmes: 
[Github](https://github.com/robinvdvleuten/vuex-persistedstate)
[BuiltForVue](https://www.builtforvue.com/#/robinvdvleuten/vuex-persistedstate)

**Comment by abishekrsrikaanth** [comment]
@MathijsHaakman, the emoji's should work properly now. But the issue with the repository you mentioned above is that an actual emoji image is being used on this readme. Take a look at https://raw.githubusercontent.com/robinvdvleuten/vuex-persistedstate/master/README.md

An ideal fix would be to update the repository to use the correct emoji and `github` encodes the image when the app retrieves it.
