### ISSUE TITLE
Add description and website to page

### ISSUE THREAD

**Issue by MathijsHaakman** [builtforvue/ui#7]
Often, there is an example provided in the [website of the github repository.](https://user-images.githubusercontent.com/12911381/38551114-ad144fec-3cb8-11e8-9e06-2403fe3759a9.png)
At the moment, you have to go to the github page to see that url, it would be nice to include that on the page in BuiltForVue

[Repository used as example: vue-lunar-calendar](https://github.com/KimWooHyun/vue-lunar-calendar)

**Comment by abishekrsrikaanth** [comment]
![image](https://user-images.githubusercontent.com/1639302/38592226-ebe7dcd4-3d08-11e8-8a6c-91b7549850ad.png)

The link to the example/homepage is on the top right and the description should be right below the jumbotron. They are indicated on the image above.
