### ISSUE TITLE
Order by QUALITY, POPULARITY, MAINTENANCE or OVERALL

### ISSUE THREAD

**Issue by gofreddo** [builtforvue/ui#8]
I want to know which packages are the most popular or best maintained.  How can I sort by one of the attributes instead of just it always sorting by Overall?

**Comment by abishekrsrikaanth** [comment]
@gofreddo Thanks for the request. Let me add this as a feature

**Comment by abishekrsrikaanth** [comment]
Just found some time to add this feature in.

![image](https://i.imgur.com/468XlcH.gif)
